# Generated by Django 3.0.7 on 2020-06-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
