# Generated by Django 3.0.7 on 2020-06-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videoUrl',
            new_name='url',
        ),
    ]
