# Generated by Django 3.0.7 on 2020-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='titleImageUrl',
            field=models.CharField(default='https://nonprofits.agileventures.org/images/big_picture.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
