# Generated by Django 3.0.7 on 2020-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_titleimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='titleImageUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
