# Generated by Django 3.0.7 on 2020-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('jwt_auth', '0002_auto_20200606_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='users', to='sports.Sport'),
        ),
    ]
