# Generated by Django 3.0.7 on 2020-06-14 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20200614_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follo',
            field=models.ManyToManyField(blank=True, related_name='_user_follo_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='_user_follow_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
