# Generated by Django 3.0.7 on 2020-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('jwt_auth', '0003_auto_20200606_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='sports',
            field=models.ManyToManyField(related_name='users', to='sports.Sport'),
        ),
    ]
