# Generated by Django 3.0.7 on 2020-06-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_auto_20200614_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
