# Generated by Django 3.0.7 on 2020-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20200609_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, default='https://www.tenforums.com/geek/gars/images/2/types/thumb__ser.png', max_length=300),
        ),
    ]
