# Generated by Django 3.0.7 on 2020-06-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0011_auto_20200609_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
