# Generated by Django 3.0.7 on 2020-06-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='text',
        ),
        migrations.AddField(
            model_name='chat',
            name='text_list',
            field=models.ManyToManyField(to='chat.ChatText'),
        ),
    ]
