# Generated by Django 3.0.7 on 2020-06-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200616_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='text_list',
        ),
        migrations.AddField(
            model_name='chat',
            name='text',
            field=models.CharField(default='hey', max_length=600),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatText',
        ),
    ]
