# Generated by Django 3.0.7 on 2020-06-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imageUrl',
            new_name='url',
        ),
    ]
