# Generated by Django 3.0.7 on 2020-06-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
