# Generated by Django 3.0.7 on 2020-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20200608_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='limit',
            field=models.IntegerField(default=1),
        ),
    ]
