# Generated by Django 3.0.7 on 2020-06-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_training_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='students',
        ),
    ]
